# Generated by Django 3.2.3 on 2021-07-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Closed', 'Closed'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='Cart', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='store/product/images'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Elo', 'Elo'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Dinheiro', 'Dinheiro')], max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
