# Generated by Django 3.2.3 on 2021-07-15 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='estimated_delivery',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
