# Generated by Django 3.2.3 on 2021-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210715_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=1024, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
